//! Protocol configuration endpoints.
//!
//! All handlers require authentication (enforced by middleware).
//! Configs are persisted in the SQLite `protocol_configs` table, seeded
//! from `config.toml` at first startup. Each protocol has a well-known
//! schema used for type validation on update.

use axum::Json;
use axum::extract::Extension;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use sqlx::SqlitePool;
use std::sync::Arc;
use tokio::sync::Mutex;

use crate::errors::ApiError;
use crate::protocol_runtime::{
    ProtocolRuntime, build_onvif_config_from_json, extract_gb28181_config,
};
use crate::stream_manager::StreamManager;
use security::middleware::AuthenticatedUser;
/// Type alias for the shared DB pool (for web CRUD operations).
pub type Db = SqlitePool;
// ---------------------------------------------------------------------------
// Schema definitions — generated from Rust config structs via `schemars`.
// Numeric / boolean fields sent as strings are coerced (for backward
// compatibility with older frontends). Unknown fields are rejected.
// ---------------------------------------------------------------------------

/// Generate a JSON Schema for the given protocol's config struct.
/// The schema is derived at compile time from the Rust type definitions,
/// eliminating the need for a hand-maintained field table.
fn schema_for(protocol: &str) -> serde_json::Value {
    let schema = match protocol {
        "onvif" => schemars::schema_for!(crate::config::OnvifConfig),
        "gb28181" => schemars::schema_for!(crate::config::Gb28181Config),
        "rtmp_push" => schemars::schema_for!(crate::config::RtmpPushConfig),
        "recording" => schemars::schema_for!(crate::config::RecordingConfig),
        "webrtc" => schemars::schema_for!(crate::config::WebRtcConfig),
        "watermark" => schemars::schema_for!(crate::config::WatermarkConfig),
        _ => return serde_json::json!({}),
    };
    serde_json::to_value(&schema).unwrap_or_else(|_| serde_json::json!({}))
}

fn type_name(v: &serde_json::Value) -> &'static str {
    match v {
        serde_json::Value::Null => "null",
        serde_json::Value::Bool(_) => "bool",
        serde_json::Value::Number(_) => "number",
        serde_json::Value::String(_) => "string",
        serde_json::Value::Array(_) => "array",
        serde_json::Value::Object(_) => "object",
    }
}

/// Coerce a JSON number-or-numeric-string into u64, bounded by [min, max].
fn coerce_uint(v: serde_json::Value, min: u64, max: u64) -> Result<u64, String> {
    match v {
        serde_json::Value::Number(n) => {
            let as_u64 = n
                .as_u64()
                .ok_or_else(|| format!("expected integer, got float {:?}", n))?;
            if as_u64 < min || as_u64 > max {
                return Err(format!(
                    "integer {} out of range [{}, {}]",
                    as_u64, min, max
                ));
            }
            Ok(as_u64)
        }
        // Accept numeric strings from legacy frontends.
        serde_json::Value::String(s) => {
            let parsed: i64 = s
                .parse()
                .map_err(|_| format!("expected integer, got string {:?}", s))?;
            if parsed < 0 {
                return Err(format!(
                    "integer {} out of range [{}, {}]",
                    parsed, min, max
                ));
            }
            let parsed_u64 = parsed as u64;
            if parsed_u64 < min || parsed_u64 > max {
                return Err(format!(
                    "integer {} out of range [{}, {}]",
                    parsed_u64, min, max
                ));
            }
            Ok(parsed_u64)
        }
        other => Err(format!("expected integer, got {}", type_name(&other))),
    }
}

/// Extract a u64 from a JSON Schema constraint value, handling both integer
/// and float representations that schemars may emit (e.g. `65535` vs `65535.0`).
fn schema_u64(v: Option<&serde_json::Value>, default: u64) -> u64 {
    v.and_then(|v| v.as_u64().or_else(|| v.as_f64().map(|f| f as u64)))
        .unwrap_or(default)
}

/// Resolve a `$ref` (e.g. `#/definitions/Gb35114Config`) against the root
/// schema, returning the referenced subschema. Non-ref schemas pass through.
/// schemars 0.8 wraps struct fields in `{"allOf": [{$ref}]}` when they carry
/// a `default` — unwrap that too.
fn resolve_ref<'a>(
    root: &'a serde_json::Value,
    schema: &'a serde_json::Value,
) -> &'a serde_json::Value {
    if let Some(all_of) = schema.get("allOf").and_then(|a| a.as_array())
        && all_of.len() == 1
    {
        return resolve_ref(root, &all_of[0]);
    }
    let ref_path = match schema.get("$ref").and_then(|r| r.as_str()) {
        Some(r) => r,
        None => return schema,
    };
    // Only `#/definitions/Name` refs are generated by schemars 0.8.
    ref_path
        .strip_prefix("#/definitions/")
        .and_then(|name| root.get("definitions").and_then(|d| d.get(name)))
        .unwrap_or(schema)
}

/// Validate + coerce a JSON object against an object schema's `properties`.
/// Rejects unknown keys at every nesting level and coerces leaf values.
fn validate_object(
    root: &serde_json::Value,
    obj_schema: &serde_json::Value,
    obj: &serde_json::Map<String, serde_json::Value>,
) -> Result<serde_json::Value, String> {
    let empty_map = serde_json::Map::new();
    let properties = obj_schema
        .get("properties")
        .and_then(|p| p.as_object())
        .unwrap_or(&empty_map);

    for k in obj.keys() {
        if !properties.contains_key(k) {
            return Err(format!("unknown field {:?}", k));
        }
    }

    let mut out = serde_json::Map::new();
    for (k, v) in obj {
        let prop_schema = resolve_ref(root, properties.get(k).expect("checked above"));
        let coerced = coerce_value(root, prop_schema, v.clone())
            .map_err(|e| format!("field {:?}: {}", k, e))?;
        out.insert(k.clone(), coerced);
    }
    Ok(serde_json::Value::Object(out))
}

/// Coerce a JSON value to match the type declared in the (ref-resolved)
/// property schema. Object values recurse so nested config sections get the
/// same unknown-field rejection and legacy-string coercion as the top level.
fn coerce_value(
    root: &serde_json::Value,
    prop_schema: &serde_json::Value,
    v: serde_json::Value,
) -> Result<serde_json::Value, String> {
    if let serde_json::Value::Object(ref inner) = v {
        let schema = resolve_ref(root, prop_schema);
        if schema.get("properties").is_some() {
            return validate_object(root, schema, inner);
        }
    }
    coerce_leaf(prop_schema, v)
}

/// Coerce a JSON value to match the type declared in the JSON Schema property.
/// Boolean and numeric fields sent as strings are coerced for backward
/// compatibility with legacy frontends.
fn coerce_leaf(
    prop_schema: &serde_json::Value,
    v: serde_json::Value,
) -> Result<serde_json::Value, String> {
    let ty = prop_schema
        .get("type")
        .and_then(|t| t.as_str())
        .unwrap_or("");
    match ty {
        "boolean" => match v {
            serde_json::Value::Bool(_) => Ok(v),
            // Accept string "true" / "false" from legacy frontends.
            serde_json::Value::String(s) => match s.parse::<bool>() {
                Ok(b) => Ok(serde_json::Value::Bool(b)),
                Err(_) => Err(format!("expected bool, got string {:?}", s)),
            },
            other => Err(format!("expected bool, got {}", type_name(&other))),
        },
        "integer" => {
            let min = schema_u64(prop_schema.get("minimum"), 0);
            let max = schema_u64(prop_schema.get("maximum"), u64::MAX);
            coerce_uint(v, min, max).map(serde_json::Value::from)
        }
        "string" => match v {
            serde_json::Value::String(ref s) => {
                // Enum-constrained strings (e.g. watermark.position) must be
                // one of the schema's declared values.
                if let Some(allowed) = prop_schema.get("enum").and_then(|e| e.as_array())
                    && !allowed.iter().any(|a| a.as_str() == Some(s.as_str()))
                {
                    let values = allowed
                        .iter()
                        .filter_map(|a| a.as_str())
                        .collect::<Vec<_>>()
                        .join(", ");
                    return Err(format!("value {s:?} not in [{values}]"));
                }
                // maxLength (char count) when the schema declares one.
                if let Some(max_len) = prop_schema.get("maxLength")
                    && let Some(max_len) = max_len
                        .as_u64()
                        .or_else(|| max_len.as_f64().map(|f| f as u64))
                    && s.chars().count() as u64 > max_len
                {
                    return Err(format!(
                        "string length {} exceeds maxLength {max_len}",
                        s.chars().count()
                    ));
                }
                Ok(v)
            }
            other => Err(format!("expected string, got {}", type_name(&other))),
        },
        _ => Ok(v),
    }
}

/// Validate + coerce a partial update payload against the generated JSON Schema.
/// Returns the coerced object containing only known fields (at every nesting
/// level). Unknown fields trigger an error.
pub(crate) fn validate_and_coerce(
    protocol: &str,
    payload: &serde_json::Value,
) -> Result<serde_json::Value, String> {
    let obj = match payload.as_object() {
        Some(o) => o,
        None => {
            return Err(format!(
                "expected JSON object for {} config update, got {}",
                protocol,
                type_name(payload)
            ));
        }
    };

    let schema = schema_for(protocol);
    match validate_object(&schema, &schema, obj) {
        Ok(v) => Ok(v),
        Err(e) if e.starts_with("unknown field") => Err(format!(
            "{} for {} config; if this is a new setting, add it to the struct in config.rs first",
            e, protocol
        )),
        Err(e) => Err(e),
    }
}
// ---------------------------------------------------------------------------
// Generic handler helpers
// ---------------------------------------------------------------------------

async fn handle_get(db: &Db, protocol: &str) -> axum::response::Response {
    match crate::db::get_protocol_config(db, protocol).await {
        Ok(Some(v)) => (StatusCode::OK, Json(v)).into_response(),
        Ok(None) => ApiError::not_found(format!("{} config not found", protocol)).into_response(),
        Err(e) => {
            tracing::error!(error = %e, protocol, "failed to read protocol config");
            ApiError::internal("database error").into_response()
        }
    }
}
/**
 * Validate, merge, and persist a protocol config update.
 * Returns the merged config JSON on success so the caller can check
 * the `enabled` flag and act on the ProtocolRuntime.
 */
// Targeted exemption: axum's Response<Body> exceeds clippy 1.98's
// result_large_err threshold; this helper is cold-path config mutation,
// boxing the Err would ripple through every route handler for no gain.
#[allow(clippy::result_large_err)]
async fn handle_put_and_get(
    db: &Db,
    protocol: &str,
    payload: serde_json::Value,
) -> Result<serde_json::Value, axum::response::Response> {
    // 1. Validate + coerce types field-by-field.
    let validated = match validate_and_coerce(protocol, &payload) {
        Ok(v) => v,
        Err(msg) => {
            return Err(ApiError::bad_request(&msg).into_response());
        }
    };
    // 2. Merge with existing config (partial update).
    let mut current = match crate::db::get_protocol_config(db, protocol).await {
        Ok(Some(v)) => v,
        Ok(None) => serde_json::json!({}),
        Err(e) => {
            tracing::error!(error = %e, protocol, "failed to read protocol config");
            return Err(ApiError::internal("database error").into_response());
        }
    };
    if let Some(obj) = validated.as_object() {
        for (key, value) in obj {
            current[key] = value.clone();
        }
    }
    // 3. Persist merged config.
    if let Err(e) = crate::db::set_protocol_config(db, protocol, &current).await {
        tracing::error!(error = %e, protocol, "failed to persist protocol config");
        return Err(ApiError::internal("database error").into_response());
    }

    tracing::info!(protocol, "protocol config updated via Web UI");
    Ok(current)
}
// ---------------------------------------------------------------------------
// ONVIF config
// ---------------------------------------------------------------------------

/// GET /api/protocols/onvif — return ONVIF device config as JSON.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_onvif(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    handle_get(&db, "onvif").await
}

/// PUT /api/protocols/onvif — update ONVIF device config (partial, validated).
///
/// After persisting to DB, hot-toggles the ONVIF WS-Discovery server
/// based on the `enabled` flag — no server restart needed.
#[tracing::instrument(skip_all)]
pub async fn update_protocols_onvif(
    Extension(db): Extension<Db>,
    Extension(protocol_runtime): Extension<Arc<Mutex<ProtocolRuntime>>>,
    Extension(stream_manager): Extension<Arc<StreamManager>>,
    Extension(advertised_host): Extension<Arc<String>>,
    Extension(_user): Extension<AuthenticatedUser>,
    Json(payload): Json<serde_json::Value>,
) -> axum::response::Response {
    match handle_put_and_get(&db, "onvif", payload).await {
        Ok(config) => {
            let enabled = config
                .get("enabled")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let mut rt = protocol_runtime.lock().await;
            if enabled {
                let onvif_config = build_onvif_config_from_json(&config, &advertised_host);
                if let Err(e) = rt.start_onvif(onvif_config, stream_manager.clone()).await {
                    tracing::warn!(error = %e, "failed to start ONVIF after config update");
                }
            } else {
                rt.stop_onvif().await;
            }
            (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response()
        }
        Err(resp) => resp,
    }
}

// ---------------------------------------------------------------------------
// GB28181 config
// ---------------------------------------------------------------------------

/// GET /api/protocols/gb28181 — return GB28181 device config as JSON.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_gb28181(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    handle_get(&db, "gb28181").await
}

/// PUT /api/protocols/gb28181 — update GB28181 device config (partial, validated).
///
/// After persisting to DB, hot-toggles the GB28181 SIP device loop
/// based on the `enabled` flag — no server restart needed.
#[tracing::instrument(skip_all)]
pub async fn update_protocols_gb28181(
    Extension(db): Extension<Db>,
    Extension(protocol_runtime): Extension<Arc<Mutex<ProtocolRuntime>>>,
    Extension(stream_manager): Extension<Arc<StreamManager>>,
    Extension(_user): Extension<AuthenticatedUser>,
    Json(payload): Json<serde_json::Value>,
) -> axum::response::Response {
    match handle_put_and_get(&db, "gb28181", payload).await {
        Ok(config) => {
            let enabled = config
                .get("enabled")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let mut rt = protocol_runtime.lock().await;
            if enabled {
                let gb_config = extract_gb28181_config(&config);
                if let Err(e) = rt.start_gb28181(&gb_config, stream_manager).await {
                    tracing::warn!(error = %e, "failed to start GB28181 after config update");
                }
            } else {
                rt.stop_gb28181().await;
            }
            (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response()
        }
        Err(resp) => resp,
    }
}

// ---------------------------------------------------------------------------
// RTMP push config
// ---------------------------------------------------------------------------

/// GET /api/protocols/rtmp — return RTMP push config as JSON.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_rtmp(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    handle_get(&db, "rtmp_push").await
}

/// PUT /api/protocols/rtmp — update RTMP push config (partial, validated).
///
/// After persisting to DB, hot-toggles the RTMP push flag
/// based on the `enabled` flag. New streams will auto-attach RTMP output
/// when enabled; existing streams keep their RTMP output until stopped.
#[tracing::instrument(skip_all)]
pub async fn update_protocols_rtmp(
    Extension(db): Extension<Db>,
    Extension(protocol_runtime): Extension<Arc<Mutex<ProtocolRuntime>>>,
    Extension(_user): Extension<AuthenticatedUser>,
    Json(payload): Json<serde_json::Value>,
) -> axum::response::Response {
    match handle_put_and_get(&db, "rtmp_push", payload).await {
        Ok(config) => {
            let enabled = config
                .get("enabled")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let mut rt = protocol_runtime.lock().await;
            if enabled {
                if let Err(e) = rt.start_rtmp().await {
                    tracing::warn!(error = %e, "failed to enable RTMP after config update");
                }
            } else {
                rt.stop_rtmp().await;
            }
            (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response()
        }
        Err(resp) => resp,
    }
}

// ---------------------------------------------------------------------------
// Recording config
// ---------------------------------------------------------------------------

/// GET /api/protocols/recording — return local recording config as JSON.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_recording(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    handle_get(&db, "recording").await
}

/// PUT /api/protocols/recording — update local recording config (partial, validated).
///
/// Persists the config to the DB. Recording is attached at stream-creation
/// time: toggling `enabled` takes effect on the next stream start (stop +
/// start the camera to apply). Existing running streams keep their current
/// recording state until restarted.
#[tracing::instrument(skip_all)]
pub async fn update_protocols_recording(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
    Json(payload): Json<serde_json::Value>,
) -> axum::response::Response {
    match handle_put_and_get(&db, "recording", payload).await {
        Ok(_) => (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response(),
        Err(resp) => resp,
    }
}

// ---------------------------------------------------------------------------
// WebRTC config
// ---------------------------------------------------------------------------

/// GET /api/protocols/webrtc — return WebRTC streaming config as JSON.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_webrtc(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    handle_get(&db, "webrtc").await
}

/// PUT /api/protocols/webrtc — update WebRTC config (partial, validated).
///
/// Persists the config. The WebRTC runtime (WHIP/WHEP endpoints) reads this
/// flag at request time, so toggling takes effect immediately for new
/// peer connections.
#[tracing::instrument(skip_all)]
pub async fn update_protocols_webrtc(
    Extension(db): Extension<Db>,
    Extension(_user): Extension<AuthenticatedUser>,
    Json(payload): Json<serde_json::Value>,
) -> axum::response::Response {
    match handle_put_and_get(&db, "webrtc", payload).await {
        Ok(_) => (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response(),
        Err(resp) => resp,
    }
}

// ---------------------------------------------------------------------------
// Runtime status
// ---------------------------------------------------------------------------

/// GET /api/protocols/runtime-status — return running/stopped status for
/// each protocol.
#[tracing::instrument(skip_all)]
pub async fn get_protocols_runtime_status(
    Extension(protocol_runtime): Extension<Arc<Mutex<ProtocolRuntime>>>,
    Extension(_user): Extension<AuthenticatedUser>,
) -> impl IntoResponse {
    let rt = protocol_runtime.lock().await;
    let status = rt.status();
    (StatusCode::OK, Json(status)).into_response()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_coerce_bool_accepts_native() {
        let schema = json!({"type": "boolean"});
        assert_eq!(coerce_leaf(&schema, json!(true)).unwrap(), json!(true));
    }

    #[test]
    fn test_coerce_bool_coerces_string() {
        // Legacy frontend sends "true"/"false" strings.
        let schema = json!({"type": "boolean"});
        assert_eq!(coerce_leaf(&schema, json!("true")).unwrap(), json!(true));
        assert_eq!(coerce_leaf(&schema, json!("false")).unwrap(), json!(false));
    }

    #[test]
    fn test_coerce_bool_rejects_invalid() {
        let schema = json!({"type": "boolean"});
        assert!(coerce_leaf(&schema, json!("yes")).is_err());
        assert!(coerce_leaf(&schema, json!(1)).is_err());
        assert!(coerce_leaf(&schema, json!("null")).is_err());
    }

    #[test]
    fn test_coerce_integer_native() {
        let schema = json!({"type": "integer", "minimum": 0, "maximum": 65535});
        assert_eq!(coerce_leaf(&schema, json!(5060)).unwrap(), json!(5060));
        assert_eq!(coerce_leaf(&schema, json!(0)).unwrap(), json!(0));
        assert_eq!(coerce_leaf(&schema, json!(65535)).unwrap(), json!(65535));
    }

    #[test]
    fn test_coerce_integer_coerces_numeric_string() {
        // Legacy frontend sends port as "5060".
        let schema = json!({"type": "integer", "minimum": 0, "maximum": 65535});
        assert_eq!(coerce_leaf(&schema, json!("5060")).unwrap(), json!(5060));
    }

    #[test]
    fn test_coerce_integer_rejects_out_of_range() {
        let schema = json!({"type": "integer", "minimum": 0, "maximum": 65535});
        assert!(coerce_leaf(&schema, json!(65536)).is_err());
        assert!(coerce_leaf(&schema, json!(-1)).is_err());
    }

    #[test]
    fn test_coerce_integer_handles_float_constraints() {
        // schemars emits minimum/maximum as floats (e.g. 65535.0).
        let schema = json!({"type": "integer", "minimum": 0.0, "maximum": 65535.0});
        assert_eq!(coerce_leaf(&schema, json!(5060)).unwrap(), json!(5060));
        assert!(coerce_leaf(&schema, json!(65536)).is_err());
    }

    #[test]
    fn test_validate_rejects_unknown_field() {
        let payload = json!({"enabled": true, "bogus_field": "evil"});
        let err = validate_and_coerce("onvif", &payload).unwrap_err();
        assert!(err.contains("unknown field"), "got: {}", err);
        assert!(err.contains("bogus_field"), "got: {}", err);
    }

    #[test]
    fn test_validate_accepts_nested_gb35114() {
        let payload = json!({
            "gb35114": {
                "enabled": true,
                "device_cert_file": "/etc/certs/device_cert.pem",
                "device_key_file": "/etc/certs/device_key.pem",
                "platform_cert_file": "/etc/certs/platform_cert.pem",
                "server_id": "34020000002000000001"
            }
        });
        let result = validate_and_coerce("gb28181", &payload).unwrap();
        assert_eq!(result["gb35114"]["enabled"], json!(true));
        assert_eq!(
            result["gb35114"]["device_cert_file"],
            json!("/etc/certs/device_cert.pem")
        );
        assert_eq!(
            result["gb35114"]["server_id"],
            json!("34020000002000000001")
        );
        // Only the provided section is in the validated output.
        assert_eq!(result.as_object().unwrap().len(), 1);
    }

    #[test]
    fn test_validate_rejects_unknown_nested_field() {
        let payload = json!({"gb35114": {"enabled": true, "bogus": 1}});
        let err = validate_and_coerce("gb28181", &payload).unwrap_err();
        assert!(err.contains("unknown field"), "got: {}", err);
        assert!(err.contains("bogus"), "got: {}", err);
    }

    #[test]
    fn test_validate_coerces_nested_legacy_strings() {
        // Legacy frontends may send booleans as strings, including inside
        // nested sections; a string "true" must not silently become false.
        let payload = json!({"gb35114": {"enabled": "true"}});
        let result = validate_and_coerce("gb28181", &payload).unwrap();
        assert_eq!(result["gb35114"]["enabled"], json!(true));
    }

    #[test]
    fn test_validate_coerces_legacy_string_types() {
        // Simulate a legacy frontend sending all-string values.
        let payload = json!({
            "enabled": "true",
            "platform_sip_port": "5060",
            "register_interval_secs": "60"
        });
        let result = validate_and_coerce("gb28181", &payload).unwrap();
        assert_eq!(result["enabled"], json!(true));
        assert_eq!(result["platform_sip_port"], json!(5060));
        assert_eq!(result["register_interval_secs"], json!(60));
    }

    #[test]
    fn test_validate_rejects_wrong_type_for_field() {
        let payload = json!({"enabled": "not-a-bool"});
        let err = validate_and_coerce("onvif", &payload).unwrap_err();
        assert!(err.contains("expected bool"), "got: {}", err);

        let payload = json!({"platform_sip_port": "not-a-number"});
        let err = validate_and_coerce("gb28181", &payload).unwrap_err();
        assert!(err.contains("expected integer"), "got: {}", err);
    }

    #[test]
    fn test_validate_partial_update_keeps_known_only() {
        let payload = json!({"device_name": "kitchen-cam"});
        let result = validate_and_coerce("onvif", &payload).unwrap();
        assert_eq!(result["device_name"], json!("kitchen-cam"));
        // Only the provided field is in the validated output.
        assert_eq!(result.as_object().unwrap().len(), 1);
    }

    #[test]
    fn test_watermark_schema_and_validation() {
        // Schema carries the SPEC §5.2 constraints the coercion relies on.
        let schema = schema_for("watermark");
        let props = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("watermark schema must have properties");
        for key in [
            "enabled",
            "text",
            "show_timestamp",
            "timestamp_format",
            "position",
            "font_size",
            "font_path",
        ] {
            assert!(props.contains_key(key), "missing property {key}");
        }
        let pos = resolve_ref(&schema, &props["position"]);
        let allowed = pos
            .get("enum")
            .and_then(|e| e.as_array())
            .expect("position enum");
        assert!(allowed.contains(&json!("top-left")));
        assert!(allowed.contains(&json!("bottom-right")));
        let size = resolve_ref(&schema, &props["font_size"]);
        let as_f64 = |v: Option<&serde_json::Value>| v.and_then(|x| x.as_f64());
        assert_eq!(as_f64(size.get("minimum")), Some(12.0), "font_size minimum");
        assert_eq!(as_f64(size.get("maximum")), Some(96.0), "font_size maximum");
        let text = resolve_ref(&schema, &props["text"]);
        assert_eq!(as_f64(text.get("maxLength")), Some(128.0), "text maxLength");

        // Valid payload passes and coerces nothing unexpected.
        let payload = json!({"enabled": true, "text": "前门", "position": "bottom-right"});
        let result = validate_and_coerce("watermark", &payload).unwrap();
        assert_eq!(result["position"], json!("bottom-right"));

        // Enum values are enforced.
        let err = validate_and_coerce("watermark", &json!({"position": "middle"})).unwrap_err();
        assert!(err.contains("not in ["), "got: {err}");

        // Numeric range is enforced (schema minimum/maximum).
        let err = validate_and_coerce("watermark", &json!({"font_size": 5})).unwrap_err();
        assert!(err.contains("out of range"), "got: {err}");

        // Text length cap counts characters.
        let err =
            validate_and_coerce("watermark", &json!({ "text": "米".repeat(129) })).unwrap_err();
        assert!(err.contains("exceeds maxLength"), "got: {err}");

        // Unknown fields are rejected with the actionable message.
        let err = validate_and_coerce("watermark", &json!({"position": "top-left", "bogus": 1}))
            .unwrap_err();
        assert!(err.contains("unknown field"), "got: {err}");
    }

    #[test]
    fn test_schema_for_unknown_protocol_is_empty() {
        let schema = schema_for("nonexistent");
        assert!(schema.as_object().map(|o| o.is_empty()).unwrap_or(true));
    }

    #[test]
    fn test_schema_for_onvif_has_expected_properties() {
        let schema = schema_for("onvif");
        let props = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("schema must have properties");
        assert!(props.contains_key("enabled"));
        assert!(props.contains_key("device_name"));
        assert!(props.contains_key("manufacturer"));
        assert!(props.contains_key("model"));
        assert!(props.contains_key("serial"));
        assert!(props.contains_key("firmware_version"));
    }

    #[test]
    fn test_schema_for_gb28181_has_expected_properties() {
        let schema = schema_for("gb28181");
        let props = schema
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("schema must have properties");
        assert!(props.contains_key("enabled"));
        assert!(props.contains_key("platform_sip_address"));
        assert!(props.contains_key("platform_sip_port"));
        assert!(props.contains_key("device_id"));
        assert!(props.contains_key("register_interval_secs"));
        assert!(props.contains_key("talkback_playback"));
    }

    #[test]
    fn test_schema_for_gb28181_has_gb35114_section() {
        let schema = schema_for("gb28181");
        let gb = resolve_ref(&schema, &schema["properties"]["gb35114"]);
        let props = gb
            .get("properties")
            .and_then(|p| p.as_object())
            .expect("gb35114 subschema must resolve to an object with properties");
        for key in [
            "enabled",
            "device_cert_file",
            "device_key_file",
            "platform_cert_file",
            "server_id",
        ] {
            assert!(props.contains_key(key), "missing gb35114.{key}");
        }
    }
}
