[package]
name = "streaming"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
capture = { path = "../capture" }
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
opentelemetry.workspace = true
uuid.workspace = true
protocols = { path = "../protocols" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
cpal.workspace = true
parking_lot = "0.12"
observability = { path = "../observability" }

[dev-dependencies]
axum.workspace = true
http = "1"
bytes = "1"
