[package]
build = "build.rs"
name = "web"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
opentelemetry.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
anyhow.workspace = true
include_dir.workspace = true
serde.workspace = true
rusqlite.workspace = true
sqlx.workspace = true
serde_json.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
security = { path = "../security" }
observability = { path = "../observability" }
protocols = { path = "../protocols" }
gb28181-rs.workspace = true
uuid.workspace = true
capture = { path = "../capture" }
streaming = { path = "../streaming" }
axum-server.workspace = true
rustls.workspace = true
tokio-util = { version = "0.7", features = ["io"] }
futures-core.workspace = true
parking_lot.workspace = true
futures = "0.3.32"
tokio-stream = { version = "0.1", features = ["sync"] }
schemars.workspace = true
libc.workspace = true
